# Travis CI for automatic building.
#
# Changelog:
#  - 2018-09-12: added checck for OS X
#  - 2018-09-11: warning as error set to false
#  - 2018-06-29: first try

language: r
r_check_args: --as-cran
cache: packages
warnings_are_errors: false

os:
  - linux
  - osx

addons:
  apt:
    packages:
    - libnlopt-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update        ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install nlopt ; fi

## Codecov integration
r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
