# Travis CI for automatic building.
#
# Changelog:
#  - 2019-01-07: handling bioconductor
#  - 2018-12-08: coverage updated
#  - 2018-09-12: added checck for OS X
#  - 2018-09-11: warning as error set to false
#  - 2018-06-29: first try

language: r
r_check_args: --as-cran
cache: packages

warnings_are_errors: false

addons:
  apt:
    packages:
    - libnlopt-dev

brew_packages:
  - gcc
  - nlopt

r_packages:
  - covr

use_bioc: true
bioc_required: true

bioc_packages:
  - biomformat
  - phyloseq

matrix:
  include:
    - os: linux
      r: bioc-release
      after_success:
      - Rscript -e 'covr::codecov()'
      env: NB='with covr'
    - os: linux
      r: bioc-devel
    - os: osx
      r: bioc-release

before_deploy:
  - export FILE_TO_UPLOAD=$(ls _builds/*/PLNmodels*.tar.gz)

deploy:
  provider: releases
  api_key:
    - secure: "SiGdlTgQ97kHWow4KPYJv2c9roglYMKYwGeC2Tj0eaMNCTdvJoxulp4zBumWcxgHKt6AJwW0uO4wWlVQ+lqWZemUx+VYVZTX9eiOLB55RUPcEEqB/2CqgGtwt/df7VPbZ4UWv9zHZTyDXbKGgkByr9GxG4WBVQVagmiVaEQQwdrbfvH2oog3NPnhASn3ITRAqrifyuYKJeDQ3VT/GSwCB9whxiqdEuMv2JCD8IcaPlhHV67btapjGOh3CuFn7/ndzIuJJpcNmqArQt8YbuhBZEeW/GuWib6iNHeJ6HINlhmxuTrVtBZTIH/cvbv0DWaQUc8HFQnQ9a+zRH1qlSuAdQxiSLOgX2DeJ+tv2ZLU0CyFShx2qiDaRDqxs+NrqUNgutL8DPexuIrPJYezMrqG6EdSz+vY/nEJztxqFMHhBTKmcH+INeudrezbh+s8JyKKgfVp7UsJPqldSgNOqCU6bHu/W623fjjGckkkxDhBGrW/6fTXfFTQOkwAVgW7b9Ad+wYcLzzchlzaq8ehq6q0hD1+0/h1HflfqWd/XDYXbgYyYpRz7dc5PYcgISszbkrIMb/pXkGcOpAInqH7iJrmDLJpjrPsu3OcZOKB55lyfCG3/KbD0ZxCmBbwnwI+OCvoAnfZSWF/99kQkzHAtj/JCbfuYp6VmEsr6p7bOEfM3QY="
  file_glob: true
  file: "${FILE_TO_UPLOAD}"
  skip_cleanup: true
  on:
    tags: true


