# Travis CI for automatic building.
#
# Changelog:
#  - 2019-01-29: deployment of pages with travis
#  - 2019-01-28: deployment of releases with travis
#  - 2019-01-07: handling bioconductor
#  - 2018-12-08: coverage updated
#  - 2018-09-12: added check for OS X
#  - 2018-09-11: warning as error set to false
#  - 2018-06-29: first try

language: r

r_check_args: --as-cran

env:
  - PKG_TARBALL=PLNmodels_0.8.1.gz

sudo: required

cache: packages

warnings_are_errors: false

addons:
  apt:
    packages:
    - libnlopt-dev

brew_packages:
  - gcc
  - nlopt

r_packages:
  - covr
  - pkgdown

use_bioc: true
bioc_required: true

bioc_packages:
  - biomformat
  - phyloseq

matrix:
  include:
    - os: linux
      r: bioc-release
      after_success:
      - Rscript -e 'covr::codecov()'
      - R CMD INSTALL .
      - Rscript -e 'pkgdown::build_site()'
      deploy:
      - provider: pages
        skip-cleanup: true
        github-token: $GITHUB_PAT
        keep-history: true
        local-dir: docs
        on:
          branch: master
      deploy:
        - provider: releases
          api_key: $GITHUB_PAT
          file: ${PKG_TARBALL}
          skip_cleanup: true
          on:
            tags: true
    - os: linux
      r: bioc-devel
    - os: osx
      r: bioc-release
